apiVersion: v2
name: defaultFleetPlugins
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: ui-plugin-operator
    repository: https://charts.rancher.io/
    version: 103.0.2+up0.2.1